name: 'Terraform'

on:
  pull_request:


jobs:
  job-1:
    name: 'Terraform Init'
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Initialize TF code
      run: terraform init
    - name: Validate formatting on TF code
      run: terraform fmt -check
    - name: Validate TF code in all files
      run: terraform validate
